# Generated by Django 3.2.6 on 2021-09-05 10:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_pin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('pin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(max_length=30)),
                ('sub_county', models.CharField(blank=True, max_length=30, null=True)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chemical Company',
                'verbose_name_plural': 'Chemical Companies',
            },
        ),
        migrations.CreateModel(
            name='SeedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_pin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('pin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(max_length=30)),
                ('sub_county', models.CharField(blank=True, max_length=30, null=True)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seed Company',
                'verbose_name_plural': 'Seed Companies',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.TextField(blank=True, null=True)),
                ('location_pin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, srid=4326)),
                ('acreage', models.FloatField(default=0)),
                ('pin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(max_length=30)),
                ('sub_county', models.CharField(max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('total_acreage_sprayed', models.FloatField(default=0)),
                ('total_acreage_mapped', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
    ]
