# Generated by Django 3.2.6 on 2021-08-14 16:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210809_1958"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "map_type",
                    models.CharField(
                        choices=[("RGB", "RGB Map"), ("NDV", "NDVI Map")],
                        default="RGB",
                        max_length=3,
                    ),
                ),
                ("raster", django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                (
                    "plot_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.plotdetail",
                    ),
                ),
            ],
        ),
    ]
