# Generated by Django 3.2.6 on 2021-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210907_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaricomfarmer',
            name='error_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
