# Generated by Django 3.2.6 on 2021-09-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_safaricomfarmer_error_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaricomfarmer',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safaricomfarmercsv',
            name='is_update_file',
            field=models.BooleanField(default=False),
        ),
    ]
