# Generated by Django 3.2.6 on 2021-09-05 10:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chemical_type', models.CharField(choices=[('FGC', 'Fungicide'), ('IST', 'Insecticide'), ('FLR', 'Foliar'), ('RND', 'Roundup'), ('OTH', 'Other')], max_length=3)),
                ('other', models.CharField(blank=True, max_length=30, null=True)),
                ('recommended_dosage_per_ha', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('container_image', models.ImageField(blank=True, null=True, upload_to='uploads/chemicals/labels/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_manufacturer', to='accounts.chemicalcompany')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_reseller', to='accounts.chemicalcompany')),
            ],
            options={
                'verbose_name': 'Chemical',
                'verbose_name_plural': 'Chemicals',
            },
        ),
        migrations.CreateModel(
            name='FarmCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('MZE', 'Maize'), ('WHT', 'Wheat'), ('BLY', 'Barley'), ('CNL', 'Canola'), ('TEA', 'Tea'), ('CFE', 'Coffee'), ('AVD', 'Avocado'), ('BNA', 'Banana'), ('OTH', 'Other')], max_length=3)),
                ('other', models.CharField(blank=True, max_length=30, null=True)),
                ('crop_variety', models.CharField(max_length=30)),
                ('crop_planted_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_crop_yield', models.FloatField(default=0)),
                ('seed_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seedcompany')),
            ],
            options={
                'verbose_name': 'Farm Crop',
                'verbose_name_plural': 'Farm Crops',
            },
        ),
        migrations.CreateModel(
            name='PlotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('acreage', models.FloatField(default=0)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('tiles', models.URLField(blank=True, null=True)),
                ('last_crop_yield', models.FloatField(default=0)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farmcrop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
            options={
                'verbose_name': 'Plot Detail',
                'verbose_name_plural': 'Plot Detail',
            },
        ),
        migrations.CreateModel(
            name='SprayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage_spayed', models.FloatField(default=0)),
                ('date_sprayed', models.DateTimeField()),
                ('chemicals_sprayed', models.ManyToManyField(to='farm.Chemical')),
                ('farm_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plotdetail')),
            ],
            options={
                'verbose_name': 'Spray Detail',
                'verbose_name_plural': 'Spray Details',
            },
        ),
        migrations.CreateModel(
            name='PlotMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_type', models.CharField(choices=[('RGB', 'RGB Map'), ('NDV', 'NDVI Map')], default='RGB', max_length=4)),
                ('uploaded_tif', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plotdetail')),
            ],
        ),
        migrations.AddField(
            model_name='plotdetail',
            name='spray_detail',
            field=models.ManyToManyField(blank=True, to='farm.SprayDetail'),
        ),
        migrations.CreateModel(
            name='FarmPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest', models.CharField(choices=[('FAW', 'Fall Army Worm'), ('APD', 'Aphids'), ('CTW', 'Cutworms'), ('TRP', 'Thrips'), ('WVL', 'Weevils'), ('WTF', 'Whiteflies'), ('MTE', 'Mites'), ('OTH', 'Other')], max_length=3)),
                ('other', models.CharField(blank=True, max_length=30, null=True)),
                ('acreage_infested', models.FloatField(default=0)),
                ('last_treated_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plotdetail')),
                ('spray_details', models.ManyToManyField(blank=True, to='farm.SprayDetail')),
            ],
            options={
                'verbose_name': 'Farm Pest',
                'verbose_name_plural': 'Farm Pests',
            },
        ),
        migrations.CreateModel(
            name='FarmDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RST', 'Rust'), ('BST', 'Black Spot'), ('FSW', 'Fusarium Wilt'), ('OTH', 'Other')], max_length=3)),
                ('other', models.CharField(blank=True, max_length=30, null=True)),
                ('acreage_infested', models.FloatField(default=0)),
                ('last_treated_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plotdetail')),
                ('spray_details', models.ManyToManyField(blank=True, to='farm.SprayDetail')),
            ],
            options={
                'verbose_name': 'Farm Disease',
                'verbose_name_plural': 'Farm Diseases',
            },
        ),
    ]
