# Generated by Django 3.2.6 on 2021-08-09 12:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("id_number", models.IntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "location_pin",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, srid=4326
                    ),
                ),
                ("acreage", models.FloatField(default=0)),
                ("pin_number", models.CharField(blank=True, max_length=20, null=True)),
                ("county", models.CharField(max_length=30)),
                ("sub_county", models.CharField(max_length=30)),
                ("ward", models.CharField(blank=True, max_length=30, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
            },
        ),
        migrations.CreateModel(
            name="PlotDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("acreage", models.FloatField(default=0)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("crop", models.CharField(max_length=30)),
                ("crop_variety", models.CharField(max_length=30)),
                ("last_crop_yield", models.FloatField(default=0)),
                ("date_planted", models.DateTimeField(blank=True, null=True)),
                ("last_date_sprayed", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plot Detail",
                "verbose_name_plural": "Plot Detail",
            },
        ),
    ]
