# Generated by Django 3.2.6 on 2021-08-09 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="farmer",
            name="created_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plotdetail",
            name="tiles",
            field=models.URLField(blank=True, null=True),
        ),
    ]
